// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX2Mf16BNEHOU4GNjAWU9a9JP3JlfN_NY',
    appId: '1:851833416944:web:85b4057ca061a7831d6635',
    messagingSenderId: '851833416944',
    projectId: 'book-story-61e5d',
    authDomain: 'book-story-61e5d.firebaseapp.com',
    storageBucket: 'book-story-61e5d.firebasestorage.app',
    measurementId: 'G-EE404VXSCM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOcb9RZtUHN3HPL_2Lt9CNi5nusCZDkIk',
    appId: '1:851833416944:android:391d17d29bb7b0b81d6635',
    messagingSenderId: '851833416944',
    projectId: 'book-story-61e5d',
    storageBucket: 'book-story-61e5d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL9yFs1pGAyZQEy669sVcCJxa9xpyrpZc',
    appId: '1:851833416944:ios:f85c79f723c09de71d6635',
    messagingSenderId: '851833416944',
    projectId: 'book-story-61e5d',
    storageBucket: 'book-story-61e5d.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDL9yFs1pGAyZQEy669sVcCJxa9xpyrpZc',
    appId: '1:851833416944:ios:f85c79f723c09de71d6635',
    messagingSenderId: '851833416944',
    projectId: 'book-story-61e5d',
    storageBucket: 'book-story-61e5d.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDX2Mf16BNEHOU4GNjAWU9a9JP3JlfN_NY',
    appId: '1:851833416944:web:4a7a69be07cc6f371d6635',
    messagingSenderId: '851833416944',
    projectId: 'book-story-61e5d',
    authDomain: 'book-story-61e5d.firebaseapp.com',
    storageBucket: 'book-story-61e5d.firebasestorage.app',
    measurementId: 'G-XMY71DL5YC',
  );
}
